-- RPow.lean : iterated rounded multiplication over Nat, including the
-- Maker-shaped scaled square-and-multiply recursion and its error surface.

import Jaune.MulDiv

namespace Jaune

open Jaune _root_.Nat

/-!
# Iterated rounded multiplication

`mulr s c z x` is the scale- and offset-parametric rounded product
`(z * x + c) / s`.  `rpow s c x n` is the reference-shaped binary loop: its
accumulator is initialized from the low bit of `n`, then every iteration
squares the base before conditionally multiplying the accumulator.  That order
is observable under rounding and is therefore part of the definition.

The arithmetic surface stays at `Nat` altitude.  The final section supplies
guarded `B256` bridges; no word theorem hides multiplication or addition wrap.
-/

/-! ## B1 — one rounded multiplication -/

/-- A scale- and offset-parametric rounded product.  Floor is `c = 0`; the
Maker half-up instance is `c = s / 2`. -/
def mulr (s c z x : Nat) : Nat := (z * x + c) / s

/-- The residue left by a rounded product. -/
def mulrResidue (s c z x : Nat) : Nat := (z * x + c) % s

theorem mulr_eq (s c z x : Nat) : mulr s c z x = (z * x + c) / s := rfl

theorem mulrResidue_lt {s : Nat} (hs : s ≠ 0) (c z x : Nat) :
    mulrResidue s c z x < s :=
  Nat.mod_lt _ (Nat.pos_of_ne_zero hs)

/-- The exact one-step division algorithm, in additive `Nat` form. -/
theorem mulr_decomposition (s c z x : Nat) :
    s * mulr s c z x + mulrResidue s c z x = z * x + c := by
  exact Nat.div_add_mod (z * x + c) s

theorem mulr_scaled_le (s c z x : Nat) : s * mulr s c z x ≤ z * x + c :=
  Nat.mul_div_le _ _

theorem mulr_scaled_lt_add_scale {s : Nat} (hs : s ≠ 0) (c z x : Nat) :
    z * x + c < s * (mulr s c z x + 1) := by
  have h := Nat.lt_div_mul_add (a := z * x + c) (b := s) (Nat.pos_of_ne_zero hs)
  simpa [mulr, Nat.mul_add, Nat.mul_comm] using h

/-- The general lower half of the per-step error band. -/
theorem mulr_scaled_lower {s c : Nat} (hs : s ≠ 0) (hc : c < s) (z x : Nat) :
    z * x ≤ s * mulr s c z x + (s - 1 - c) := by
  have h := mulr_scaled_lt_add_scale hs c z x
  rw [Nat.mul_add, Nat.mul_one] at h
  omega

theorem div_le_mulr (s c z x : Nat) : z * x / s ≤ mulr s c z x :=
  Nat.div_le_div_right (Nat.le_add_right _ _)

theorem mulr_le_ceilDiv {s c : Nat} (hs : s ≠ 0) (hc : c < s) (z x : Nat) :
    mulr s c z x ≤ ceilDiv (z * x) s := by
  rw [mulr, ceilDiv_eq_add_sub_one_div hs]
  apply Nat.div_le_div_right
  omega

theorem mulr_le_mulr_right {z z' : Nat} (h : z ≤ z') (s c x : Nat) :
    mulr s c z x ≤ mulr s c z' x :=
  Nat.div_le_div_right (Nat.add_le_add_right (Nat.mul_le_mul_right x h) c)

theorem mulr_le_mulr_left {x x' : Nat} (h : x ≤ x') (s c z : Nat) :
    mulr s c z x ≤ mulr s c z x' :=
  Nat.div_le_div_right (Nat.add_le_add_right (Nat.mul_le_mul_left z h) c)

theorem mulr_le_mulr_offset {c c' : Nat} (h : c ≤ c') (s z x : Nat) :
    mulr s c z x ≤ mulr s c' z x :=
  Nat.div_le_div_right (Nat.add_le_add_left h (z * x))

/-- The half-up step can overshoot by at most `s / 2`. -/
theorem mulr_half_up_upper (s z x : Nat) :
    s * mulr s (s / 2) z x ≤ z * x + s / 2 :=
  mulr_scaled_le _ _ _ _

/-- The half-up step can undershoot by at most `ceilDiv s 2 - 1`. -/
theorem mulr_half_up_lower {s : Nat} (hs : s ≠ 0) (z x : Nat) :
    z * x ≤ s * mulr s (s / 2) z x + (ceilDiv s 2 - 1) := by
  have hc : s / 2 < s := by omega
  have h := mulr_scaled_lower hs hc z x
  rw [ceilDiv_eq_add_sub_one_div (by decide : (2 : Nat) ≠ 0)]
  omega

/-! ## B2 — an exact telescope over a factor list -/

def mulrChain (s c : Nat) : Nat → List Nat → Nat
  | z, [] => z
  | z, x :: xs => mulrChain s c (mulr s c z x) xs

/-- The weighted sum of the residues generated by `mulrChain`. -/
def mulrChainResidue (s c : Nat) : Nat → List Nat → Nat
  | _, [] => 0
  | z, x :: xs =>
      mulrResidue s c z x * xs.prod +
        s * mulrChainResidue s c (mulr s c z x) xs

/-- The common weight of the per-step offset in the chain telescope. -/
def mulrChainOffset (s : Nat) : List Nat → Nat
  | [] => 0
  | _ :: xs => xs.prod + s * mulrChainOffset s xs

/-- Exact residue telescope.  It is deliberately additive: no truncated
subtraction discards information needed by an invariant. -/
theorem mulrChain_telescope (s c z : Nat) (xs : List Nat) :
    s ^ xs.length * mulrChain s c z xs + mulrChainResidue s c z xs =
      z * xs.prod + c * mulrChainOffset s xs := by
  induction xs generalizing z with
  | nil => simp [mulrChain, mulrChainResidue, mulrChainOffset]
  | cons x xs ih =>
      rw [mulrChain, mulrChainResidue, mulrChainOffset, List.length_cons,
        List.prod_cons, pow_succ]
      calc
        s ^ xs.length * s * mulrChain s c (mulr s c z x) xs +
              (mulrResidue s c z x * xs.prod +
                s * mulrChainResidue s c (mulr s c z x) xs) =
            s * (s ^ xs.length * mulrChain s c (mulr s c z x) xs +
              mulrChainResidue s c (mulr s c z x) xs) +
                mulrResidue s c z x * xs.prod := by
                  simp only [Nat.mul_add, Nat.mul_assoc]
                  ac_rfl
        _ = s * (mulr s c z x * xs.prod + c * mulrChainOffset s xs) +
              mulrResidue s c z x * xs.prod := by rw [ih]
        _ = (s * mulr s c z x + mulrResidue s c z x) * xs.prod +
              c * (s * mulrChainOffset s xs) := by
                simp only [Nat.mul_add, Nat.add_mul, Nat.mul_assoc]
                ac_rfl
        _ = (z * x + c) * xs.prod + c * (s * mulrChainOffset s xs) := by
              rw [mulr_decomposition]
        _ = z * (x * xs.prod) + c * (xs.prod + s * mulrChainOffset s xs) := by
              simp only [Nat.mul_add, Nat.add_mul, Nat.mul_assoc]
              ac_rfl

theorem mulrChain_scaled_upper (s c z : Nat) (xs : List Nat) :
    s ^ xs.length * mulrChain s c z xs ≤
      z * xs.prod + c * mulrChainOffset s xs := by
  have h := mulrChain_telescope s c z xs
  omega

theorem mulrChain_scaled_lower {s c : Nat} (hs : s ≠ 0) (hc : c < s)
    (z : Nat) (xs : List Nat) :
    z * xs.prod ≤ s ^ xs.length * mulrChain s c z xs +
      (s - 1 - c) * mulrChainOffset s xs := by
  induction xs generalizing z with
  | nil => simp [mulrChain, mulrChainOffset]
  | cons x xs ih =>
      rw [mulrChain, mulrChainOffset, List.length_cons, List.prod_cons, pow_succ]
      calc
        z * (x * xs.prod) = (z * x) * xs.prod := (Nat.mul_assoc _ _ _).symm
        _ ≤ (s * mulr s c z x + (s - 1 - c)) * xs.prod :=
          Nat.mul_le_mul_right xs.prod (mulr_scaled_lower hs hc z x)
        _ = s * (mulr s c z x * xs.prod) + (s - 1 - c) * xs.prod := by
          simp only [Nat.add_mul, Nat.mul_assoc]
        _ ≤ s * (s ^ xs.length * mulrChain s c (mulr s c z x) xs +
              (s - 1 - c) * mulrChainOffset s xs) +
                (s - 1 - c) * xs.prod :=
          Nat.add_le_add_right (Nat.mul_le_mul_left s (ih (mulr s c z x))) _
        _ = s ^ xs.length * s * mulrChain s c (mulr s c z x) xs +
              (s - 1 - c) * (xs.prod + s * mulrChainOffset s xs) := by
                simp only [Nat.mul_add, Nat.mul_assoc]
                ac_rfl

theorem mulrChain_floor_le (s z : Nat) (xs : List Nat) :
    s ^ xs.length * mulrChain s 0 z xs ≤ z * xs.prod := by
  simpa using mulrChain_scaled_upper s 0 z xs

theorem mulrChain_half_up_upper (s z : Nat) (xs : List Nat) :
    s ^ xs.length * mulrChain s (s / 2) z xs ≤
      z * xs.prod + (s / 2) * mulrChainOffset s xs :=
  mulrChain_scaled_upper _ _ _ _

theorem mulrChain_half_up_lower {s : Nat} (hs : s ≠ 0) (z : Nat) (xs : List Nat) :
    z * xs.prod ≤ s ^ xs.length * mulrChain s (s / 2) z xs +
      (ceilDiv s 2 - 1) * mulrChainOffset s xs := by
  have hc : s / 2 < s := by omega
  have h := mulrChain_scaled_lower hs hc z xs
  have hcoeff : s - 1 - s / 2 = ceilDiv s 2 - 1 := by
    rw [ceilDiv_eq_add_sub_one_div (by decide : (2 : Nat) ≠ 0)]
    omega
  rw [← hcoeff]
  exact h

/-! ## B3 — reference-shaped square-and-multiply -/

def rpowLoop (s c z x n : Nat) : Nat :=
  if h : n = 0 then z
  else
    let xx := mulr s c x x
    let zx := if n % 2 = 1 then mulr s c z xx else z
    rpowLoop s c zx xx (n / 2)
termination_by n
decreasing_by omega

/-- Scaled exponentiation in the reference's operation order. -/
def rpow (s c x n : Nat) : Nat :=
  if n = 0 then s
  else rpowLoop s c (if n % 2 = 1 then x else s) x (n / 2)

/-- An annotated multiplication expression.  Offsets live on nodes so an
`rpow` tree can use half-up internally while a segment tree uses floor at its
outer composition nodes. -/
inductive RoundTree where
  | scale
  | base
  | initial
  | mul (offset : Nat) (left right : RoundTree)
deriving Repr, DecidableEq

def RoundTree.eval (s x initial : Nat) : RoundTree → Nat
  | .scale => s
  | .base => x
  | .initial => initial
  | .mul c l r => mulr s c (l.eval s x initial) (r.eval s x initial)

def rpowTreeLoop (c : Nat) (z x : RoundTree) (n : Nat) : RoundTree :=
  if h : n = 0 then z
  else
    let xx := .mul c x x
    let zx := if n % 2 = 1 then .mul c z xx else z
    rpowTreeLoop c zx xx (n / 2)
termination_by n
decreasing_by omega

def rpowTree (c n : Nat) : RoundTree :=
  if n = 0 then .scale
  else rpowTreeLoop c (if n % 2 = 1 then .base else .scale) .base (n / 2)

theorem rpowTreeLoop_eval (s c x initial : Nat) (zt xt : RoundTree) (n : Nat) :
    (rpowTreeLoop c zt xt n).eval s x initial =
      rpowLoop s c (zt.eval s x initial) (xt.eval s x initial) n := by
  induction n using Nat.strong_induction_on generalizing zt xt with
  | h n ih =>
      rw [rpowTreeLoop, rpowLoop]
      split
      · rfl
      · split
        · apply ih (n / 2) (by omega)
        · apply ih (n / 2) (by omega)

theorem rpowTree_eval (s c x n : Nat) :
    (rpowTree c n).eval s x 0 = rpow s c x n := by
  rw [rpowTree, rpow]
  split
  · rfl
  · simpa only [RoundTree.eval, apply_ite] using
      rpowTreeLoop_eval s c x 0
        (if n % 2 = 1 then .base else .scale) .base (n / 2)

end Jaune
